using public Ip

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ jobs:
 
     env:
       EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
-      EC2_PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }}
+      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
     steps:
@@ -24,11 +24,6 @@ jobs:
         with:
           python-version: 3.11
 
-      - name: Debug
-        run: |
-          echo "Username: $EC2_USERNAME"
-          echo "Private IP: $EC2_PRIVATE_IP"
-
       - name: Configure SSH
         run: |
           mkdir -p ~/.ssh
@@ -37,9 +32,21 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_PRIVATE_IP 'bash -s' << 'EOF'
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_PUBLIC_IP 'bash -s' << 'EOF'
             cd schedules_microservice
             git pull origin main
             pip install -r requirements.txt
             python3 main.py
           EOF
+
+      - name: Check HTTP Status
+        run: |
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://$EC2_PUBLIC_IP:8080)
+          echo "HTTP Status Code: $response_code"
+          if [ $response_code -ne 200 ]; then
+            echo "Error: HTTP Status Code is not 200. Marking the job as failed."
+            exit 1
+          else
+            echo "HTTP Status Code is 200. Marking the job as successful."
+            exit 0
+          fi    
